In [ ]:
import numpy as np
nums = np.array([[1,4,7], [2,5,8], [3,6,9]])
nums

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
nums = np.arange(3, 30, 3)
nums

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
zeros = np.zeros((3, 5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
ones = np.ones((3, 5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
lin = np.linspace(1, 8, 12)
lin

array([1.        , 1.63636364, 2.27272727, 2.90909091, 3.54545455,
       4.18181818, 4.81818182, 5.45454545, 6.09090909, 6.72727273,
       7.36363636, 8.        ])

In [ ]:
eye = np.eye(5)
eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
random = np.random.randint(120, 250, 10)
random

array([162, 128, 249, 137, 231, 135, 242, 224, 195, 124])

In [ ]:
full = np.full((3,5),5)
full

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [ ]:
nums = np.arange(1, 25)
print(nums)
reshape = nums.reshape(4, 6)
print(reshape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [ ]:
indexing = np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]))
print(indexing)
print(indexing[0,3])
print(indexing[3,2])
print(indexing[:,0])
print(indexing[:3,:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
4
15
[ 1  5  9 13]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


In [ ]:
slicing = np.arange(20)
print(slicing)
print(slicing[1:19:3])
print(slicing[:8])
print(slicing[1:9])
print(slicing[::2])
print(slicing[4:])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  4  7 10 13 16]
[0 1 2 3 4 5 6 7]
[1 2 3 4 5 6 7 8]
[ 0  2  4  6  8 10 12 14 16 18]
[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
import numpy as np
nums = np.arange(20).reshape(4, 5)
print(nums)
print(nums.ndim)
print(nums.shape)
print(nums.size)
print(nums.dtype.name)
print(nums.itemsize)
print(nums.data)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
2
(4, 5)
20
int64
8


In [ ]:
import numpy as np
nums1 = np.array([30,39,81,145,167])
nums2 = np.array([3,6,9,12,15])
print(np.add(nums1,nums2))
print(np.subtract(nums1,nums2))
print(np.multiply(nums1,nums2))
print(np.divide(nums1,nums2))
print(np.floor_divide(nums1,nums2))

[ 33  45  90 157 182]
[ 27  33  72 133 152]
[  90  234  729 1740 2505]
[10.          6.5         9.         12.08333333 11.13333333]
[10  6  9 12 11]


In [ ]:
import numpy as np
nums1 = np.array([12,13,14,15,16])
nums2 = np.array([3,6,9,12,15])
nums3 = nums1 - nums2
print(nums3)

[9 7 5 3 1]
