In [ ]:
import numpy as np
nums1 = np.array([30,39,81,145,167])
nums2 = np.array([3,6,9,12,15])
print(np.add(nums1,nums2))
print(np.subtract(nums1,nums2))
print(np.multiply(nums1,nums2))
print(np.divide(nums1,nums2))
print(np.floor_divide(nums1,nums2))

[ 33  45  90 157 182]
[ 27  33  72 133 152]
[  90  234  729 1740 2505]
[10.          6.5         9.         12.08333333 11.13333333]
[10  6  9 12 11]


In [ ]:
import numpy as np
nums = np.array([[30,39,81,145,167], [3,6,9,12,15]])
print("Min: ", np.min(nums))
print("Max: ", np.max(nums))
print("Mean: ", np.mean(nums))
print("Median: ", np.median(nums))
print("Std: ", np.std(nums))
print("Var: ", np.var(nums))
print("4th Percentile: ", np.percentile(nums, 4))
print("any: ", np.any(nums))
print("all: ", np.all(nums))

Min:  3
Max:  167
Mean:  50.7
Median:  22.5
Std:  57.1717587625219
Var:  3268.6099999999997
4th Percentile:  4.08
any:  True
all:  True


In [ ]:
import numpy as np
nums1 = np.array([30,39,81,145,167])
nums2 = np.array([3,6,9,12,15])
print(np.add(nums1,nums2))


[ 33  45  90 157 182]


In [ ]:
import numpy as np
nums1 = np.array([[5,10,15,20,25],[30,35,40,45,50],[55,60,65,70,75]])
nums2 = np.array([3,6,9,12,15])
print(nums1)
print(nums2)
print(nums1+nums2)

[[ 5 10 15 20 25]
 [30 35 40 45 50]
 [55 60 65 70 75]]
[ 3  6  9 12 15]
[[ 8 16 24 32 40]
 [33 41 49 57 65]
 [58 66 74 82 90]]
