In [ ]:
import numpy as np
single = np.random.RandomState(55)
x = single.randint(250, size=12)
print("x: ", (x))
y = [ 5, 8, 11]
print("y; ", (x[y]))
z = np.array([[2, 4],
             [6, 8]])
print("z: ", (x[z]))

x:  [205 154  39 200 125  29 189 229  55  37  91 161]
y;  [ 29  55 161]
z:  [[ 39 125]
 [189  55]]


In [ ]:
import numpy as np
multi = np.arange(30).reshape((5, 6))
print("x: ", multi)
row = np.array([2, 3, 4])
col = np.array([1, 2, 3])
print("y: ", multi[row, col])
print("z: ", multi[row[:, np.newaxis], col])
print("a: ", row[:, np.newaxis] * col)

x:  [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
y:  [13 20 27]
z:  [[13 14 15]
 [19 20 21]
 [25 26 27]]
a:  [[ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]]


In [ ]:
import numpy as np
multi = np.arange(30).reshape((5, 6))
print("x: ", multi)
print("y: ", multi[3, [5, 3, 1]])

x:  [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
y:  [23 21 19]


In [ ]:
import numpy as np
multi = np.arange(30).reshape((5, 6))
print("x: ", multi)
print("y: ", multi[2:, [5, 3, 1]])

x:  [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
y:  [[17 15 13]
 [23 21 19]
 [29 27 25]]


In [ ]:
import numpy as np
x = np.array([7, 6, 3, 6, 8, 9, 2, 1, 4, 7, 5])
z = np.argsort(x)
print("argsort: ", z)
y = np.sort(x)
print("np.sort: ", y)
x.sort()
print("sort: ", x)


argsort:  [ 7  6  2  8 10  1  3  0  9  4  5]
np.sort:  [1 2 3 4 5 6 6 7 7 8 9]
sort:  [1 2 3 4 5 6 6 7 7 8 9]


In [ ]:
import numpy as np
rand = np.random.RandomState(25)
x = rand.randint(0, 20, (4, 5))
print("x: ", x)
y = np.sort(x, axis=0)
print("column: ", y)
z = np.sort(x, axis=1)
print("row: ", z)

x:  [[ 4 15 12 18  8]
 [ 4  5  1  7  3]
 [ 3 13  3  1 16]
 [15  9 16 12 13]]
column:  [[ 3  5  1  1  3]
 [ 4  9  3  7  8]
 [ 4 13 12 12 13]
 [15 15 16 18 16]]
row:  [[ 4  8 12 15 18]
 [ 1  3  4  5  7]
 [ 1  3  3 13 16]
 [ 9 12 13 15 16]]


In [ ]:
import numpy as np
x = np.array([4, 5, 2, 8, 5, 7, 9, 2, 8, 6, 7])
print("x: ", x)
y = np.partition(x, 3)
print("y: ", y)

x:  [4 5 2 8 5 7 9 2 8 6 7]
y:  [2 2 4 5 5 6 7 9 8 8 7]


In [ ]:
import numpy as np
rand = np.random.RandomState(25)
x = rand.randint(0, 20, (5, 7))
print("x: ", x)
z = np.partition(x, 2, axis=1)
print("z: ", z)

x:  [[ 4 15 12 18  8  4  5]
 [ 1  7  3  3 13  3  1]
 [16 15  9 16 12 13 18]
 [ 4  9  0 10 15 10  1]
 [17 18  4  2  5  8 11]]
z:  [[ 4  4  5 18  8 15 12]
 [ 1  1  3  3 13  3  7]
 [ 9 12 13 16 15 16 18]
 [ 0  1  4 10 15 10  9]
 [ 2  4  5 17 18  8 11]]
